# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27c07debba811ccef99b9df2dec49eca5b3af2368533c3b64266ed29e129957397a7feef52617a25ca3c08c60754aa39d6abb46e445b74b6afa1c6820103083

test:
  secret_key_base: 9e848982ded86b0aab7eb20aed82c38037ecb23e989d44e3bb6d5dc48f37ca8feb3382b44d2e9b9d573b2fc313bb34dda1e23c62bc5ff6aa59e36c0583223a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
